config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :terminal_workplaces, only: [:index]
  resource :duck_terminal, only: [:new, :show]
  get "reports/duplicate_terminal_ips"
  resources :ti_clients do
    resources :remote_pin_plus, module: :ti_clients, only: [:index] 
    resources :terminals, module: :ti_clients, only: [:index] do
      member do
        post :assign
        post :pairing
        post :begin_session
        post :end_session
        post :add
        post :change_correlation
      end
      collection do
        post :reconnect_all
        post :assign_all
        post :pairing_all
      end
    end
    resources :kt_proxies, module: :ti_clients, only: [:index] do
      collection do
        put :fetch
      end
    end
  end
  resources :kt_proxies
  get "idle_messages", to: "idle_messages#index", as: :idle_messages
  get "idle_messages/edit"
  put "idle_messages", to: "idle_messages#update"

  resources 'situation_picture', only: [:index, :update] do
    collection do
      get :failed
    end
  end
  get 'verify_pins', to: 'verify_pins#index'
  post 'verify_pins', to: 'verify_pins#verify'
  get "client_certificates/import_p12", to: "client_certificates#import_p12",
      as: "import_p12_client_certificate"
  resources :client_certificates
  resources :workplaces do
    collection do
      get :new_import
      post :import
      delete :delete_outdated
    end
  end
  resources :networks
  resources :notes, only: [:show, :index, :edit, :update, :destroy] do
    collection do
      get :sindex
    end
  end
  resources :logs, only: [:show, :index, :update, :destroy] do
    collection do
      get :sindex
      put :invalidate_outdated
      delete :delete_outdated
    end
    resources :notes, module: :logs
  end
  get "search", to: 'searches#index'
  resources :operational_states
  resources :cards do
    resources :logs, only: [:index, :show, :destroy], module: :cards
    collection do
      get :sindex
      delete :delete_expired
    end
    member do
      get :copy
      post :get_certificate
      post :get_pin_status
      post :verify_pin
      post :get_card
    end
    resources :notes, module: :cards do
      collection do
        get :sindex
      end
    end
    resources :card_certificates, module: :cards, only: [:index, :show] do
      collection do
        post :fetch
      end
    end
  end

  post "card_terminals", to: "card_terminals#index", 
                         constraints: lambda {|req| req.format == :json}
  resources :card_terminals do
    resources :logs, only: [:index, :show, :destroy], module: :card_terminals
    collection do
      get :sindex
      get :new_arp
      post :arp_check
    end
    member do
      post :check
      get  :edit_identification
      get  :edit_idle_message
      post :fetch_idle_message
      post :fetch_proxy
      put  :update_idle_message
      get  :ping
      post :reboot
      post :remote_pairing
      get  :test_context_form
      post :test_context
    end
    resources :notes, module: :card_terminals do
      collection do
        get :sindex
      end
    end
    resources :card_certificates, module: :card_terminals do
      collection do
        post :fetch
      end
    end
    resource :kt_proxy, module: :card_terminals
  end
  resources :card_certificates, only: [:show, :index]
  resources :contexts
  resources :connector_contexts, only: [:show, :update]
  resources :connectors do
    collection do
      get :sindex
    end
    member do
      post :check
      post :fetch_sds
      post :get_resource_information
      post :get_card_terminals
      post :get_cards
      get :ping
      post :reboot
      get :test_context_form
      post :test_context
    end
    resources :logs, only: [:index, :show, :destroy], module: :connectors
    resources :card_terminals, only: [:index, :show, :destroy], module: :connectors
    resources :cards, only: [:index, :show, :destroy], module: :connectors
    resources :notes, module: :connectors do
      collection do
        get :sindex
      end
    end
    resource :ti_client, module: :connectors
  end
  resources :locations do
    resources :connectors, only: [:index, :show, :destroy], module: :locations
    resources :card_terminals, only: [:index, :show, :destroy], module: :locations
    resources :cards, only: [:index, :show, :destroy], module: :locations
    resources :networks, only: [:index, :show, :destroy], module: :locations
  end
  root to: 'home#index'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  mount Wobauth::Engine, at: '/auth'
  authenticate :user, ->(user) { user.is_admin? } do
    mount GoodJob::Engine => "good_job"
  end

end

app/models/home.rb
class Home
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/_card_states.html.erb
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::OK,
                  count: Card.ok.count,
                  link:  sindex_cards_path(condition: Cocard::States::OK),
                  myframe: 'cards') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::WARNING,
                  count: Card.warning.count,
                  link:  sindex_cards_path(condition: Cocard::States::WARNING),
                  myframe: 'cards') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::CRITICAL,
                  count: Card.critical.count,
                  link:  sindex_cards_path(condition: Cocard::States::CRITICAL),
                  myframe: 'cards') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::UNKNOWN,
                  count: Card.unknown.count,
                  link:  sindex_cards_path(condition: Cocard::States::UNKNOWN),
                  myframe: 'cards') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::NOTHING,
                  count: Card.nothing.count,
                  link:  sindex_cards_path(condition: Cocard::States::NOTHING),
                  myframe: 'cards') %>
</div>
<div class="me-2">
  <%= link_to sindex_cards_path(acknowledged: 'true'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'cards' do %>
    <i class="fa-solid fa-person-digging"></i>
    <span class="badge text-bg-secondary">
      <%= Card.acknowledged.count %>
    </span>
  <% end %>
</div>

app/views/home/_card_terminal_states.html.erb
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::OK,
                  count: CardTerminal.ok.count,
                  link:  sindex_card_terminals_path(condition: Cocard::States::OK),
                  myframe: 'card_terminals') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::WARNING,
                  count: CardTerminal.warning.count,
                  link:  sindex_card_terminals_path(condition: Cocard::States::WARNING),
                  myframe: 'card_terminals') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::CRITICAL,
                  count: CardTerminal.critical.count,
                  link:  sindex_card_terminals_path(condition: Cocard::States::CRITICAL),
                  myframe: 'card_terminals') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::UNKNOWN,
                  count: CardTerminal.unknown.count,
                  link:  sindex_card_terminals_path(condition: Cocard::States::UNKNOWN),
                  myframe: 'card_terminals') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::NOTHING,
                  count: CardTerminal.nothing.count,
                  link:  sindex_card_terminals_path(condition: Cocard::States::NOTHING),
                  myframe: 'card_terminals') %>
</div>
<div class="me-2">
  <%= link_to sindex_card_terminals_path(acknowledged: 'true'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'card_terminals' do %>
    <i class="fa-solid fa-person-digging"></i>
    <span class="badge text-bg-secondary">
      <%= CardTerminal.acknowledged.count %>
    </span>
  <% end %>
</div>

app/views/home/_card_terminals.html.erb
<div id="failed_card_terminals">
 <% if card_terminals.size > 0 %>
  <%= content_tag :table,
        id: "card_terminals_table",
        class: "table tablesm mb-0" do %>
    <thead>
      <tr class="">
            <th class="text-center"><%= t('attributes.condition') %></th>
            <th><%= t('attributes.location') %></th>
            <th><%= t('attributes.name') %></th>
            <th><%= t('attributes.connector') %></th>
            <th><%= t('attributes.condition_message') %></th>
            <th class="text-center"><%= t('attributes.updated_at') %></th>
      </tr>
    </thead>
    <tbody>
      <% card_terminals.each do |card_terminal| %>
        <%= content_tag(:tr, id: dom_id(card_terminal), class: dom_class(card_terminal)) do %>
          <td class="text-center">
            <%= render ConditionIconComponent.new(item: card_terminal, small: true) %>
          </td>
          <td><%= card_terminal.location&.lid %></td>
          <td><%= link_to(
                    card_terminal.name, 
                    card_terminal_path(card_terminal), 
                    class: "primary-link") %></td>
          <td><%= link_to(
                    card_terminal.connector&.name, 
                    connector_path(card_terminal.connector), 
                    class: "primary-link") unless card_terminal.connector.nil? %></td>
          <td><%= card_terminal.condition_message %></td>
          <td><%= card_terminal.updated_at&.localtime %></td>
        <% end %>
      <% end %>
    </tbody>
  <% end %>
 <% end %>
</div>

app/views/home/_cards.html.erb
<div id="failed_cards">
 <% if cards.size > 0 %>
  <%= content_tag :table,
        id: "cards_table",
        class: "table tablesm mb-0" do %>
    <thead>
      <tr class="">
        <th class="text-center"><%= t('attributes.condition') %></th>
        <th><%= t('attributes.card_type') %></th>
        <th><%= t('attributes.name') %></th>
        <th><%= t('attributes.condition_message') %></th>
        <th><%= t('attributes.iccsn') %></th>
        <th><%= t('attributes.connector') %></th>
        <th><%= t('attributes.card_terminal') %></th>
      </tr>
    </thead>
    <tbody>
      <% cards.each do |card| %>
        <%= content_tag(:tr, id: dom_id(card)) do %>
          <td class="text-center">
            <%= render ConditionIconComponent.new(item: card, small: true) %>
          </td>
          <td><%= card.card_type %></td>
          <td><%= card.name %></td>
          <td><%= card.condition_message %></td>
          <td><%= link_to card.iccsn, card_path(card) %></td>
          <td><%= link_to(card.card_terminal&.connector,
                          connector_path(card.card_terminal&.connector)
                         ) if card.card_terminal&.connector %></td>
          <td><%= link_to(card.card_terminal&.ct_id,
                          card_terminal_path(card.card_terminal)
                         ) if card.card_terminal %></td>
        <% end %>
      <% end %>
    </tbody>
  <% end %>
 <% end %>
</div>

app/views/home/_connector_states.html.erb
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::OK,
                  count: Connector.ok.count,
                  link:  sindex_connectors_path(condition: Cocard::States::OK),
                  myframe: 'connectors') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::WARNING,
                  count: Connector.warning.count,
                  link:  sindex_connectors_path(condition: Cocard::States::WARNING),
                  myframe: 'connectors') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::CRITICAL,
                  count: Connector.critical.count,
                  link:  sindex_connectors_path(condition: Cocard::States::CRITICAL),
                  myframe: 'connectors') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::UNKNOWN,
                  count: Connector.unknown.count,
                  link:  sindex_connectors_path(condition: Cocard::States::UNKNOWN),
                  myframe: 'connectors') %>
</div>
<div class="me-2">
  <%= render ConditionBadgeComponent
             .new(state: Cocard::States::NOTHING,
                  count: Connector.nothing.count,
                  link:  sindex_connectors_path(condition: Cocard::States::NOTHING),
                  myframe: 'connectors') %>
</div>
<div class="me-2">
  <%= link_to sindex_connectors_path(acknowledged: 'true'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'connectors' do %>
    <i class="fa-solid fa-person-digging"></i>
    <span class="badge text-bg-secondary">
      <%= Connector.acknowledged.count %>
    </span>
  <% end %>
</div>

app/views/home/_connectors.html.erb
<div id="failed_connectors">
 <% if connectors.size > 0 %>
  <%= content_tag :table,
        id: "connectors_table",
        class: "table tablesm mb-0" do %>
    <thead>
      <tr class="">
            <th class="text-center"><%= t('attributes.condition') %></th>
            <th><%= t('attributes.name') %></th>
            <th><%= t('attributes.condition_message') %></th>
            <th class="text-center"><%= t('attributes.last_check') %></th>
            <th class="text-center"><%= t('attributes.last_check_ok') %></th>
      </tr>
    </thead>
    <tbody>
      <% connectors.each do |connector| %>
        <%= content_tag(:tr, id: dom_id(connector), class: dom_class(connector)) do %>
          <td class="text-center">
            <%= render ConditionIconComponent.new(item: connector, small: true) %>
          </td>
          <td><%= link_to(
                    connector.name, 
                    connector_path(connector), 
                    class: "primary-link") %></td>
          <td><%= connector.condition_message %></td>
          <td><%= connector.last_check&.localtime %></td>
          <td><%= connector.last_check_ok&.localtime %></td>
        <% end %>
      <% end %>
    </tbody>
  <% end %>
 <% end %>
</div>

app/views/home/_log_types.html.erb
<div class="me-2">
  <%= link_to sindex_logs_path(type: 'Connector'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'logs' do %>
    Konnektoren
    <span class="badge text-bg-secondary">
      <%= Log.valid.not_acknowledged.where(loggable_type: 'Connector').count %>
    </span>
  <% end %>
</div>

<div class="me-2">
  <%= link_to sindex_logs_path(type: 'CardTerminal'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'logs' do %>
    Kartenterminals
    <span class="badge text-bg-secondary">
      <%= Log.valid.not_acknowledged.where(loggable_type: 'CardTerminal').count %>
    </span>
  <% end %>
</div>

<div class="me-2">
  <%= link_to sindex_logs_path(type: 'Card'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'logs' do %>
    Karten
    <span class="badge text-bg-secondary">
      <%= Log.valid.not_acknowledged.where(loggable_type: 'Card').count %>
    </span>
  <% end %>
</div>

<div class="me-2">
  <%= link_to sindex_logs_path(acknowledged: 'true'),
              class: 'btn btn-outline-secondary',
              "data-turbo-frame": 'logs' do %>
    <i class="fa-solid fa-person-digging"></i>
    <span class="badge text-bg-secondary">
      <%= Log.valid.acknowledged.count %>
    </span>
  <% end %>
</div>

app/views/home/index.html.erb
<%= turbo_stream_from :home %>
<%= turbo_stream_from :notes %>
<%= turbo_stream_from :verify_pins %>

<% if current_user.present? %>
  <div class="container-fluid">
    <div class="row">
      <% unless Note.object_notes.active.current.count > 0 %>
        <div class="col-xl"></div>
      <% end %>
      <div class="col-xl-10">
        <div class="card mb-3">
          <div class="card-header">
            <div class="row">
              <div class="col-xs-5 col-md-4 col-ml-3">
              <h4 class="me-4 pt-1">Konnektoren</h4>
              </div>
              <div class="d-flex col-xs-7 col-md-8 col-ml-9">
                <%= render 'connector_states' %>
              </div>
            </div>
          </div>
          <div>
            <%= turbo_frame_tag("connectors", src: sindex_connectors_path, refresh: "morph") %>
          </div>
        </div>

        <div class="card mt-3">
          <div class="card-header">
            <div class="row">
              <div class="col-xs-5 col-md-4 col-ml-3">
                <h4 class="me-4 pt-1">Karten</h4>
              </div>
              <div class="d-flex col-xs-7 col-md-8 col-ml-9">
                <%= render 'card_states' %>
                <% if can? :verify, VerifyPin %>
                  <div class="ms-auto">
                    <%= link_to t('controller.verify_pins'), verify_pins_path,
                                class: 'btn btn-outline-secondary' ,
                                data: { 'turbo-frame' => '_top' }
                     %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div>
            <%= turbo_frame_tag("cards", src: sindex_cards_path, refresh: "morph") %>
          </div>
        </div>

        <div class="card mt-3">
          <div class="card-header">
            <div class="row">
              <div class="col-xs-5 col-md-4 col-ml-3">
                <h4 class="me-4 pt-1">Ereignisse</h4>
              </div>
              <div class="d-flex col-xs-7 col-md-8 col-ml-9">
                <%= render 'log_types' %>
              </div>
            </div>
          </div>
          <div>
            <%= turbo_frame_tag("logs", src: sindex_logs_path, refresh: "morph") %>
          </div>
        </div>

        <div class="card mt-3">
          <div class="card-header">
            <div class="row">
              <div class="col-xs-5 col-md-4 col-ml-3">
                <h4 class="me-4 pt-1">Kartenterminals</h4>
              </div>
              <div class="d-flex col-xs-7 col-md-8 col-ml-9">
                <%= render 'card_terminal_states' %>
              </div>
            </div>
          </div>
          <div>
            <%= turbo_frame_tag("card_terminals", src: sindex_card_terminals_path, refresh: "morph") %>
          </div>
        </div>
      </div>
      <% unless Note.object_notes.active.current.count > 0 %>
        <div class="col-xl"></div>
      <% else %>
        <div class="col-xl-2">
          <div class="mb-3">
            <%= turbo_frame_tag("home_side_notes", src: sindex_notes_path, refresh: "morph") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <p>
   Sie sind nicht eingeloggt.
   <%= link_to "Bitte loggen Sie sich ein", wobauth.new_user_session_path %>
  </p>
<% end %>