config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :terminal_workplaces, only: [:index]
  resource :duck_terminal, only: [:new, :show]
  get "reports/duplicate_terminal_ips"
  resources :ti_clients do
    resources :remote_pin_plus, module: :ti_clients, only: [:index] 
    resources :terminals, module: :ti_clients, only: [:index] do
      member do
        post :assign
        post :pairing
        post :begin_session
        post :end_session
        post :add
        post :change_correlation
      end
      collection do
        post :reconnect_all
        post :assign_all
        post :pairing_all
      end
    end
    resources :kt_proxies, module: :ti_clients, only: [:index] do
      collection do
        put :fetch
      end
    end
  end
  resources :kt_proxies
  get "idle_messages", to: "idle_messages#index", as: :idle_messages
  get "idle_messages/edit"
  put "idle_messages", to: "idle_messages#update"

  resources 'situation_picture', only: [:index, :update] do
    collection do
      get :failed
    end
  end
  get 'verify_pins', to: 'verify_pins#index'
  post 'verify_pins', to: 'verify_pins#verify'
  get "client_certificates/import_p12", to: "client_certificates#import_p12",
      as: "import_p12_client_certificate"
  resources :client_certificates
  resources :workplaces do
    collection do
      get :new_import
      post :import
      delete :delete_outdated
    end
  end
  resources :networks
  resources :notes, only: [:show, :index, :edit, :update, :destroy] do
    collection do
      get :sindex
    end
  end
  resources :logs, only: [:show, :index, :update, :destroy] do
    collection do
      get :sindex
      put :invalidate_outdated
      delete :delete_outdated
    end
    resources :notes, module: :logs
  end
  get "search", to: 'searches#index'
  resources :operational_states
  resources :cards do
    resources :logs, only: [:index, :show, :destroy], module: :cards
    collection do
      get :sindex
      delete :delete_expired
    end
    member do
      get :copy
      post :get_certificate
      post :get_pin_status
      post :verify_pin
      post :get_card
    end
    resources :notes, module: :cards do
      collection do
        get :sindex
      end
    end
    resources :card_certificates, module: :cards, only: [:index, :show] do
      collection do
        post :fetch
      end
    end
  end

  post "card_terminals", to: "card_terminals#index", 
                         constraints: lambda {|req| req.format == :json}
  resources :card_terminals do
    resources :logs, only: [:index, :show, :destroy], module: :card_terminals
    collection do
      get :sindex
      get :new_arp
      post :arp_check
    end
    member do
      post :check
      get  :edit_identification
      get  :edit_idle_message
      post :fetch_idle_message
      post :fetch_proxy
      put  :update_idle_message
      get  :ping
      post :reboot
      post :remote_pairing
      get  :test_context_form
      post :test_context
    end
    resources :notes, module: :card_terminals do
      collection do
        get :sindex
      end
    end
    resources :card_certificates, module: :card_terminals do
      collection do
        post :fetch
      end
    end
    resource :kt_proxy, module: :card_terminals
  end
  resources :card_certificates, only: [:show, :index]
  resources :contexts
  resources :connector_contexts, only: [:show, :update]
  resources :connectors do
    collection do
      get :sindex
    end
    member do
      post :check
      post :fetch_sds
      post :get_resource_information
      post :get_card_terminals
      post :get_cards
      get :ping
      post :reboot
      get :test_context_form
      post :test_context
    end
    resources :logs, only: [:index, :show, :destroy], module: :connectors
    resources :card_terminals, only: [:index, :show, :destroy], module: :connectors
    resources :cards, only: [:index, :show, :destroy], module: :connectors
    resources :notes, module: :connectors do
      collection do
        get :sindex
      end
    end
    resource :ti_client, module: :connectors
  end
  resources :locations do
    resources :connectors, only: [:index, :show, :destroy], module: :locations
    resources :card_terminals, only: [:index, :show, :destroy], module: :locations
    resources :cards, only: [:index, :show, :destroy], module: :locations
    resources :networks, only: [:index, :show, :destroy], module: :locations
  end
  root to: 'home#index'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  mount Wobauth::Engine, at: '/auth'
  authenticate :user, ->(user) { user.is_admin? } do
    mount GoodJob::Engine => "good_job"
  end

end

app/models/cocard/card.rb
module Cocard
  class Card

    ATTRIBUTES = %i( properties card_handle card_type iccsn
                     insert_time card_holder_name expiration_date object_system_version )

    def initialize(hash)
      @hash = hash || {}
    end

    def properties
      hash
    end

    def ct_id
      hash[:ct_id]
    end

    def card_handle
      hash[:card_handle]
    end

    def card_type
      hash[:card_type]
    end

    def iccsn
      hash[:iccsn]
    end

    def slotid
      hash[:slot_id]&.to_i
    end

    def insert_time
      hash[:insert_time]
    end

    def card_holder_name
      hash[:card_holder_name]
    end

    def expiration_date
      hash[:certificate_expiration_date]
    end

    def card_version
      Cocard::CardVersion.new(hash[:card_version])
    end

    def object_system_version
      card_version.object_system_version
    end

  private
    attr_reader :hash
  end
end

app/controllers/cards/card_certificates_controller.rb
module Cards
  class CardCertificatesController < CardCertificatesController
    before_action :set_certable

    def fetch
      card = @certable
      if card.certable?
        Cards::FetchCertificates.new(card: card).call do |result|
          result.on_success do |message, card_certificates|
            flash[:success] = "#{card.iccsn} #{card.card_type}: #{message}"
          end

          result.on_failure do |message|
            flash[:alert] = "#{card.iccsn} #{card.card_type}: #{message}"
          end
        end
      else
        flash[:warning] = "#{card.iccsn} #{card.card_type} wird nicht unterstützt!"
      end
      respond_with(@certable, location: card_path(@certable))
    end

    private

    def set_certable
      @certable = Card.find(params[:card_id])
    end

    def add_breadcrumb_show
      # add_breadcrumb_for([set_certable, @note])
    end
  end
end

app/controllers/cards/logs_controller.rb
module Cards
  class LogsController < LogsController
    before_action :set_loggable

  private
    def set_loggable
      @loggable = Card.find(params[:card_id])
    end

   def add_breadcrumb_show
     # add_breadcrumb_for([set_loggable, @log])
   end

  end
end

app/controllers/cards/notes_controller.rb
module Cards
  class NotesController < NotesController
    before_action :set_notable

    private

    def set_notable
      @notable = Card.find(params[:card_id])
    end

    def add_breadcrumb_show
      # add_breadcrumb_for([set_notable, @note])
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_load_and_authorize_resource
  before_action :set_card, only: %i[show edit update destroy
                                    copy get_certificate get_pin_status
                                    verify_pin get_card]
  authorize_resource
  before_action :add_breadcrumb_show, only: [:show]

  # GET /cards
  def index
    if @locatable
      @cards = @locatable.cards
    else
      @cards = Card.all
    end

    if search_params.present?
      @cards = @cards.left_outer_joins(:location, :operational_state)
      @cards = Cards::Query.new(@cards, search_params).all
    end

    respond_with(@cards)
  end

  def sindex
    if params[:condition]
      @cards = Card.condition(params[:condition])
    elsif params[:acknowledged]
      @cards = Card.acknowledged
    else
      @cards = Card.current.failed.not_acknowledged
    end
    ordered = @cards
    @pagy, @cards = pagy(ordered, count: ordered.count)
    respond_with(@cards)
  end

  # GET /cards/1
  def show
    if @card.card_type == 'SMC-B' and @card.contexts.empty?
      flash[:notice] = t('cards.no_contexts_assigned')
    end
    respond_with(@card)
  end

  # GET /cards/new
  def new
    @card = Card.new
    respond_with(@card)
  end

  # GET /cards/1/edit
  def edit
  end

  def copy
    card = Card.find(params[:id])
    @card = @card.dup || Card.new
    @card.iccsn = ''
    @card.operational_state_id = nil
    @card.description = card.description
    @card.private_information = card.private_information
  end

  # POST /cards
  def create
    @card = Card.new(card_params)

    @card.save
    respond_with(@card)
  end

  # PATCH/PUT /cards/1
  def update
    @card.update(card_params)
    respond_with(@card)
  end

  def get_certificate
      result = Cocard::GetCertificate.new(card: @card).call
    unless result.success?
      @card.errors.add(:base, :invalid)
      @card.errors.add(:base, result.error_messages.join("; "))
      flash[:alert] = result.error_messages.join(', ')
    end
    respond_with(@card, action: :show)
  end

  def get_pin_status
    if set_context
      result = Cocard::GetPinStatus.new(card: @card, context: set_context).call
      unless result.success?
        status  = :alert
        message = (@card.to_s + "<br/>" +
                   "Kontext: #{@context}<br/>ERROR:: " +
                   result.error_messages.join(', ')).html_safe
      else
        if result.pin_status&.pin_status == 'VERIFIED'
          status  = :success
        else
          status  = :warning
        end
        message = "Kontext: #{@context}, " +
                  "PIN-Status: #{result.pin_status.pin_status}, " +
                  "left_tries: #{result.pin_status.left_tries}"
      end
    else
      status  = :alert
      message = "No context assigned or context not found!"
    end
    render turbo_stream: [
      turbo_stream.prepend("toaster", partial: "shared/turbo_toast",
                                      locals: {status: status, message: message}),
      turbo_stream.replace(@card, partial: "cards/show",
                                      locals: { card: @card })
    ]
  end

  def verify_pin
    ct = @card.card_terminal
    if !set_context
      status  = :alert
      message = "No context assigned or context not found!"
    elsif ct.pin_mode == 'off'
      status  = :alert
      message = "CardTerminal #{ct} pin mode == off"
    else
      # start background rmi job
      CardTerminals::RMI::VerifyPinJob.perform_later(card: @card)
      # wait some time
      sleep 3

      # start verify pin
      result = Cocard::VerifyPin.new(card: @card, context: set_context).call
      unless result.success?
        status  = :alert
        message = (@card.to_s + "<br/>" +
                            "Kontext: #{@context}<br/>ERROR:: " +
                            result.error_messages.join(', ')).html_safe
      else
        status  = :success
        message = (@card.to_s + "<br/>" + "Kontext: #{@context}<br/>" +
                   "VERIFY PIN successful").html_safe
      end
    end

    @card.save
    render turbo_stream: [
      turbo_stream.prepend("toaster", partial: "shared/turbo_toast",
                                      locals: {status: status, message: message}),
      turbo_stream.replace(@card, partial: "cards/show",
                                      locals: { card: @card })
    ]
  end

  def get_card
      result = Cocard::GetCard.new(card: @card, context: set_context).call
      unless result.success?
        status  = :alert
        message = "Kontext: #{@context} / ERROR:: " + result.error_messages.join(', ')
      else
        status  = :success
        message = "Karte im Kontext: #{@context} aktualisiert"
    end
    @card.save
    render turbo_stream: [
      turbo_stream.prepend("toaster", partial: "shared/turbo_toast",
                                      locals: { status: status, message: message }),
      turbo_stream.replace(@card, partial: "cards/show",
                                      locals: { card: @card })
    ]
  end

  # DELETE /cards/1
  def destroy
    @card.soft_delete
    respond_with(@card, location: polymorphic_path([@locatable, :cards]))
  end

  def delete_expired
    @cards = Card.where("expiration_date < ?", 4.weeks.before(Time.current))
                 .where(card_terminal_slot_id: nil)
    @cards.update_all(deleted_at: Time.current)
    redirect_to cards_path(expired: true)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.with_deleted.find(params[:id])
    end

    def set_context
      @context ||= if params[:context_id]
                     Context.find(params[:context_id])
                   else
                     nil
                   end
    end

    # Only allow a trusted parameter "white list" through.
    def card_params
      params.require(:card)
            .permit(:name, :description, :iccsn, :card_type,
                    :card_holder_name, :location_id,
                    :operational_state_id, :lanr, :bsnr, :telematikid,
                    :fachrichtung, :context_id, :private_information,
                    :card_terminal_slot_id, :tag_list_input,
                    :cert_subject_title, :cert_subject_sn, :cert_subject_givenname,
                    :cert_subject_street, :cert_subject_postalcode, :cert_subject_l,
                    :cert_subject_o, :cert_subject_cn, :expiration_date,
                    card_contexts_attributes: [
                      :id, :context_id, :_destroy
                    ])
    end

    def search_params
      searchparms = params.permit(*submit_parms, Card.attribute_names,
                                  :description, :slotid, :expired, :outdated,
                                  :search, :operational, :operational_state, :lid,
                                  :acknowledged, :deleted, :connector_id,
                                  :limit).to_h
      searchparms.reject do |k, v|
        v.blank? || submit_parms.include?(k) || non_search_params.include?(k)
      end
    end

    def submit_parms
      [ "utf8", "authenticity_token", "commit", "format", "view" ]
    end

    def non_search_params
      [ ]
    end

end

app/controllers/connectors/card_terminals_controller.rb
module Connectors
  class CardTerminalsController < CardTerminalsController
    before_action :set_locatable

  private
    def set_locatable
      @locatable = Connector.find(params[:connector_id])
    end

   def add_breadcrumb_show
     add_breadcrumb_for([set_locatable, @card_terminal])
   end

  end
end

app/controllers/connectors/cards_controller.rb
module Connectors
  class CardsController < CardsController
    before_action :set_connector


    def index
      @cards = Cards::Query.new(Card.all, connector_id: @connector.id).all
    end

  private
    def set_connector
      @connector = Connector.find(params[:connector_id])
    end

   def add_breadcrumb_show
     # add_breadcrumb_for([set_locatable, @card_terminal])
   end

  end
end

app/controllers/connectors/logs_controller.rb
module Connectors
  class LogsController < LogsController
    before_action :set_loggable

  private
    def set_loggable
      @loggable = Connector.find(params[:connector_id])
    end

    def add_breadcrumb_show
      # add_breadcrumb_for([set_loggable, @log])
    end

  end
end

app/controllers/connectors/notes_controller.rb
module Connectors
  class NotesController < NotesController
    before_action :set_notable

    private

    def set_notable
      @notable = Connector.find(params[:connector_id])
    end

    def add_breadcrumb_show
      # add_breadcrumb_for([set_notable, @note])
    end
  end
end

app/controllers/connectors/ti_clients_controller.rb
module Connectors
  class TIClientsController < TIClientsController
    before_action :set_connector

    private

    def set_connector
      @connector = Connector.find(params[:connector_id])
    end

    def add_breadcrumb_show
      # add_breadcrumb_for([set_notable, @note])
    end
  end
end

app/controllers/locations/cards_controller.rb
module Locations
  class CardsController < CardsController
    before_action :set_locatable

  private
    def set_locatable
      @locatable = Location.find(params[:location_id])
    end

#    def add_breadcrumb_show
#      add_breadcrumb_for([set_locatable, @log])
#    end

  end
end

app/controllers/locations/connectors_controller.rb
module Locations
  class ConnectorsController < ConnectorsController
    before_action :set_locatable

  private
    def set_locatable
      @locatable = Location.find(params[:location_id])
    end

#    def add_breadcrumb_show
#      add_breadcrumb_for([set_locatable, @log])
#    end

  end
end

app/views/connectors/cards/index.html.erb
<%= render 'shared/turbo-cache-control' %>

<%= turbo_frame_tag('connector_cards') do %>
<div class="card my-3">
  <div class="card-header">
    <div class="d-flex w-100">
      <div class="d-flex w-100 justify-content-between">
        <h4 class="title">
          <%= link_to @connector.name, connector_path(@connector),
                      class: 'primary-link',
                      data: { "turbo-frame" => "_top" }
           %>
          &#8227; SMC-Bs
        </h4>
        <div role="toolbar" class="pt-0">
          <%= link_to raw(%Q[<i class="fas fa-table"></i>]),
                connector_cards_path(@connector),
                class: 'btn btn-outline-secondary btn-sm',
                data: { "turbo-frame" => "_top" }
           %>
        </div>
      </div>
    </div>
  </div>
  <div class="m-2">
    <div data-controller="datatables">
      <%= content_tag :table, role: :datatable,
            id: "connector_cards_table",
            class: "table table-sm table-responsive",
            data: {
              'datatables-target': 'datatable',
              order: [[0, 'asc']].to_json
            } do %>
        <thead>
          <tr>
            <th><%= t('attributes.condition') %></th>
            <th class="notvisible"><%= t('attributes.condition_message') %></th>
            <th class="notvisible"><%= t('attributes.card_type') %></th>
            <th class="notvisible"><%= t('attributes.name') %></th>
            <th class="text-start"><%= t('attributes.iccsn') %></th>
            <th class="notvisible"><%= t('attributes.connector') %></th>
            <th><%= t('attributes.ct_id_and_slot') %></th>
            <th><%= t('attributes.card_terminal') %></th>
            <th><%= t('attributes.mac') %></th>
            <th class="text-center notvisible"><%= t('attributes.slotid') %></th>
            <th class="notvisible"><%= t('attributes.card_handle') %></th>
            <th class="notvisible"><%= t('attributes.description') %></th>
            <th class="notvisible"><%= t('attributes.insert_time') %></th>
            <th><%= t('attributes.card_holder_name') %></th>
            <th><%= t('attributes.expiration_date') %></th>
            <th class="notvisible"><%= t('attributes.object_system_version') %></th>
            <th class="notvisible"><%= t('attributes.operational_state') %></th>
            <th class="notvisible"><%= t('attributes.location') %></th>
            <th><%= t('controller.tags') %></th>
            <th class="notvisible"><%= t('attributes.lanr') %></th>
            <th class="notvisible"><%= t('attributes.bsnr') %></th>
            <th class="notvisible"><%= t('attributes.telematikid') %></th>
            <th class="notvisible"><%= t('attributes.fachrichtung') %></th>
            <th class="notvisible"><%= t('attributes.cert_subject_cn') %></th>
            <th class="notvisible"><%= t('attributes.cert_subject_title') %></th>
            <th class="notvisible"><%= t('attributes.cert_subject_sn') %></th>
            <th class="notvisible"><%= t('attributes.cert_subject_givenname') %></th>
            <th class="notvisible"><%= t('attributes.cert_subject_street') %></th>
            <th class="notvisible"><%= t('attributes.cert_subject_postalcode') %></th>
            <th class="notvisible"><%= t('attributes.cert_subject_l') %></th>
            <th class="notvisible"><%= t('attributes.cert_subject_o') %></th>
            <th ><%= t('attributes.last_ok') %></th>
            <th class="notvisible"><%= t('attributes.last_check') %></th>
          </tr>
        </thead>
        <tfoot class="search">
          <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th class="nosearch"></th>
          </tr>
        </tfoot>
        <tbody>
          <% @cards.each do |card| %>
            <%= content_tag(:tr, id: dom_id(card)) do %>
              <td class="text-center">
                <%= render ConditionIconComponent.new(item: card, small: true, as_text: true) %>
                <span style="visibility:hidden;"><%= card.condition %></span>
              </td>
              <td><%= card.condition_message %></td>
              <td><%= card.card_type %></td>
              <td><%= card.name %></td>
              <td><%= link_to card.iccsn, card_path(card), 
                              class: 'primary-link',
                              data: { 'turbo-frame' => '_top', 'turbo-prefetch' => true }
                   %></td>
              <td><%= link_to(card.card_terminal&.connector&.name, 
                              connector_path(card.card_terminal&.connector),
                              class: 'primary-link',
                              data: { 'turbo-frame' => '_top', 'turbo-prefetch' => true }
                             ) if card.card_terminal&.connector %></td>
              <td><%= link_to( "#{card.card_terminal&.ct_id}/" + 
                               "#{card.slotid}",
                               card_terminal_path(card.card_terminal),
                               class: 'primary-link',
                              data: { 'turbo-frame' => '_top', 'turbo-prefetch' => true }
                             ) if card.card_terminal %></td>
              <td><%= card.card_terminal&.name %></td>
              <td class="text-center"><%= card.card_terminal&.mac&.gsub(/:/, '') %></td>
              <td class="text-center"><%= card.slotid %></td>
              <td><%= card.card_handle %></td>
              <td><%= card.description %></td>
              <td><%= card.insert_time&.localtime %></td>
              <td><%= card.card_holder_name %></td>
              <td><%= render ExpirationDateComponent.new(item: card) %></td>
              <td><%= card.object_system_version %></td>
              <td><%= card.operational_state %></td>
              <td><%= card.location %></td>
              <td>
                <%= render TagListComponent.new(item: card) %>
              </td>
              <td><%= card.lanr %></td>
              <td><%= card.bsnr %></td>
              <td><%= card.telematikid %></td>
              <td><%= card.fachrichtung %></td>
              <td><%= card.cert_subject_cn %></td>
              <td><%= card.cert_subject_title %></td>
              <td><%= card.cert_subject_sn %></td>
              <td><%= card.cert_subject_givenname %></td>
              <td><%= card.cert_subject_street %></td>
              <td><%= card.cert_subject_postalcode %></td>
              <td><%= card.cert_subject_l %></td>
              <td><%= card.cert_subject_o %></td>
              <td>
                <%= render IsCurrentComponent.new(item: card, attr: :last_ok) %>
              </td>
              <td>
                <%= render IsCurrentComponent.new(item: card, attr: :last_check) %>
              </td>

            <% end %>
          <% end %>
        </tbody>
      <% end %>
    </div>
  </div>
</div>
<% end %>