config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :terminal_workplaces, only: [:index]
  resource :duck_terminal, only: [:new, :show]
  get "reports/duplicate_terminal_ips"
  resources :ti_clients do
    resources :remote_pin_plus, module: :ti_clients, only: [:index] 
    resources :terminals, module: :ti_clients, only: [:index] do
      member do
        post :assign
        post :pairing
        post :begin_session
        post :end_session
        post :add
        post :change_correlation
      end
      collection do
        post :reconnect_all
        post :assign_all
        post :pairing_all
      end
    end
    resources :kt_proxies, module: :ti_clients, only: [:index] do
      collection do
        put :fetch
      end
    end
  end
  resources :kt_proxies
  get "idle_messages", to: "idle_messages#index", as: :idle_messages
  get "idle_messages/edit"
  put "idle_messages", to: "idle_messages#update"

  resources 'situation_picture', only: [:index, :update] do
    collection do
      get :failed
    end
  end
  get 'verify_pins', to: 'verify_pins#index'
  post 'verify_pins', to: 'verify_pins#verify'
  get "client_certificates/import_p12", to: "client_certificates#import_p12",
      as: "import_p12_client_certificate"
  resources :client_certificates
  resources :workplaces do
    collection do
      get :new_import
      post :import
      delete :delete_outdated
    end
  end
  resources :networks
  resources :notes, only: [:show, :index, :edit, :update, :destroy] do
    collection do
      get :sindex
    end
  end
  resources :logs, only: [:show, :index, :update, :destroy] do
    collection do
      get :sindex
      put :invalidate_outdated
      delete :delete_outdated
    end
    resources :notes, module: :logs
  end
  get "search", to: 'searches#index'
  resources :operational_states
  resources :cards do
    resources :logs, only: [:index, :show, :destroy], module: :cards
    collection do
      get :sindex
      delete :delete_expired
    end
    member do
      get :copy
      post :get_certificate
      post :get_pin_status
      post :verify_pin
      post :get_card
    end
    resources :notes, module: :cards do
      collection do
        get :sindex
      end
    end
    resources :card_certificates, module: :cards, only: [:index, :show] do
      collection do
        post :fetch
      end
    end
  end

  post "card_terminals", to: "card_terminals#index", 
                         constraints: lambda {|req| req.format == :json}
  resources :card_terminals do
    resources :logs, only: [:index, :show, :destroy], module: :card_terminals
    collection do
      get :sindex
      get :new_arp
      post :arp_check
    end
    member do
      post :check
      get  :edit_identification
      get  :edit_idle_message
      post :fetch_idle_message
      post :fetch_proxy
      put  :update_idle_message
      get  :ping
      post :reboot
      post :remote_pairing
      get  :test_context_form
      post :test_context
    end
    resources :notes, module: :card_terminals do
      collection do
        get :sindex
      end
    end
    resources :card_certificates, module: :card_terminals do
      collection do
        post :fetch
      end
    end
    resource :kt_proxy, module: :card_terminals
  end
  resources :card_certificates, only: [:show, :index]
  resources :contexts
  resources :connector_contexts, only: [:show, :update]
  resources :connectors do
    collection do
      get :sindex
    end
    member do
      post :check
      post :fetch_sds
      post :get_resource_information
      post :get_card_terminals
      post :get_cards
      get :ping
      post :reboot
      get :test_context_form
      post :test_context
    end
    resources :logs, only: [:index, :show, :destroy], module: :connectors
    resources :card_terminals, only: [:index, :show, :destroy], module: :connectors
    resources :cards, only: [:index, :show, :destroy], module: :connectors
    resources :notes, module: :connectors do
      collection do
        get :sindex
      end
    end
    resource :ti_client, module: :connectors
  end
  resources :locations do
    resources :connectors, only: [:index, :show, :destroy], module: :locations
    resources :card_terminals, only: [:index, :show, :destroy], module: :locations
    resources :cards, only: [:index, :show, :destroy], module: :locations
    resources :networks, only: [:index, :show, :destroy], module: :locations
  end
  root to: 'home#index'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  mount Wobauth::Engine, at: '/auth'
  authenticate :user, ->(user) { user.is_admin? } do
    mount GoodJob::Engine => "good_job"
  end

end

app/controllers/card_terminals/card_certificates_controller.rb
module CardTerminals
  class CardCertificatesController < CardCertificatesController
    before_action :set_certable

    def fetch
      # -- get Cards
      connector = @certable.connector
      ctx       = connector.contexts.first
      result = Cocard::GetCards.new(connector:  connector, context: ctx,
                                    ct_id: @certable.ct_id).call
      if result.success?
        cards = []
        result.cards.each do |cc|
          creator = Cards::Creator.new(connector: connector, cc: cc, context: ctx)
          if creator.save
            cards << creator.card
          end
        end
        ok_msgs = []
        err_msgs = []
        cards.each do |card|
          next unless card.certable?
          Cards::FetchCertificates.new(card: card).call do |result|
            result.on_success do |message, card_certificates|
              ok_msgs << "#{card.iccsn} #{card.card_type}: #{message}"
            end

            result.on_failure do |message|
              err_msgs << "#{card.iccsn} #{card.card_type}: #{message}"
            end
          end
        end
        flash[:success] = ok_msgs.join("; ") if ok_msgs.any?
        flash[:alert] = err_msgs.join("; ") if err_msgs.any?
      else
        flash[:alert] = "Karten können nicht gelesen werden"
      end
      redirect_to card_terminal_card_certificates_path(@certable)
    end

    private

    def set_certable
      @certable = CardTerminal.find(params[:card_terminal_id])
    end

    def add_breadcrumb_show
      # add_breadcrumb_for([set_certable, @note])
    end
  end
end

app/controllers/card_terminals/kt_proxies_controller.rb
module CardTerminals
  class KTProxiesController < KTProxiesController
    before_action :set_proxyable

    private

    def set_proxyable
      @proxyable = CardTerminal.find(params[:card_terminal_id])
    end

    def add_breadcrumb_show
      # add_breadcrumb_for([set_proxyable, @note])
    end
  end
end

app/controllers/card_terminals/logs_controller.rb
module CardTerminals
  class LogsController < LogsController
    before_action :set_loggable

  private
    def set_loggable
      @loggable = CardTerminal.find(params[:card_terminal_id])
    end

   def add_breadcrumb_show
     # add_breadcrumb_for([set_loggable, @log])
   end

  end
end

app/controllers/card_terminals/notes_controller.rb
module CardTerminals
  class NotesController < NotesController
    before_action :set_notable

    private

    def set_notable
      @notable = CardTerminal.find(params[:card_terminal_id])
    end

    def add_breadcrumb_show
      # add_breadcrumb_for([set_notable, @note])
    end
  end
end

app/controllers/card_terminals_controller.rb
class CardTerminalsController < ApplicationController
  skip_load_and_authorize_resource
  before_action :set_card_terminal, only: %i[show edit update destroy
                                             check edit_identification 
                                             edit_idle_message 
                                             fetch_idle_message fetch_proxy
                                             update_idle_message
                                             ping reboot remote_pairing
                                             test_context_form test_context]
  authorize_resource
  before_action :add_breadcrumb_show, only: [:show]

  # GET /card_terminals
  def index
    if @locatable
      @card_terminals = @locatable.card_terminals
    else
      @card_terminals = CardTerminal.all
    end
    @card_terminals = @card_terminals
                      .left_outer_joins(:location, :connector, card_terminal_slots: :card)
                      .distinct

    @card_terminals = CardTerminals::Query.new(@card_terminals, search_params).all
    @filter = search_params

    respond_with(@card_terminals) do |format|
      format.json { render json: CardTerminalsDatatable.new(@card_terminals, view_context) }
    end
  end

  def sindex
    if params[:condition]
      @card_terminals = CardTerminal.condition(params[:condition])
    elsif params[:acknowledged]
      @card_terminals = CardTerminal.acknowledged
    else
      @card_terminals = CardTerminal.current.failed.not_acknowledged
    end
    ordered = @card_terminals.order('last_ok desc NULLS LAST')
    @pagy, @card_terminals = pagy(ordered, count: ordered.count)
    respond_with(@card_terminals)
  end

  # GET /card_terminals/1
  def show
    @kt_proxy  = @card_terminal.kt_proxy
    @ti_client = @card_terminal.kt_proxy&.ti_client
    fetch_terminal
    check_default_context

    respond_with(@card_terminal)
  end

  def ping
    respond_with(@card_terminal) do |format|
    end
  end

  def check
    CardTerminals::HealthCheckJob.perform_now(card_terminal: @card_terminal,
                                              user: current_user)
    respond_with(@card_terminal) do |format|
      format.turbo_stream { head :ok }
    end
  end

  # GET /card_terminals/new
  def new
    @card_terminal = CardTerminal.new
    respond_with(@card_terminal)
  end

  # GET /card_terminals/1/edit
  def edit
  end

  # POST /card_terminals
  def create
    @card_terminal = CardTerminal.new(card_terminal_params)

    @card_terminal.save
    respond_with(@card_terminal)
  end

  # PATCH/PUT /card_terminals/1
  def update
    @card_terminal.update(card_terminal_params)
    respond_with(@card_terminal)
  end

  def edit_identification
    respond_with(@card_terminal)
  end

  def fetch_idle_message
    unless CardTerminals::RMI::GetIdleMessageJob.perform_now(card_terminal: @card_terminal)
      flash[:alert] = "Abfrage des Ruhebildschirms fehlgeschlagen!"
    end
    redirect_to @card_terminal
  end

  def edit_idle_message
    respond_with(@card_terminal)
  end

  def update_idle_message
    idle_message = idle_message_params['idle_message']

    @card_terminal.rmi.set_idle_message(idle_message) do |result|
      result.on_failure do |message|
        errormsg = "Setzen des Ruhebildschirms fehlgeschlagen!"
        Rails.logger.debug("DEBUG:: update_idle_message: #{errormsg}")
        flash.now[:alert] = errormsg
      end

      result.on_success do |message|
        @card_terminal.update(idle_message: idle_message)
        @card_terminal.reload
      end

      result.on_unsupported do
        flash[:alert] = "Kartenterminal wird nicht unterstützt"
      end
    end

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: [
          turbo_stream.replace(@card_terminal, partial: "card_terminals/show",
                                               locals: { card_terminal: @card_terminal }),
          turbo_stream.update('flash',  partial: "shared/flash_alert")
        ]
      }
    end
  end

  def remote_pairing
    @card_terminal.rmi.remote_pairing do |result|
      result.on_failure do |message|
        errormsg = "Remote Pairing fehlgeschlagen - " + message
        Rails.logger.debug("DEBUG:: remote_pairing: #{errormsg}")
        flash.now[:alert] = errormsg
      end

      result.on_success do |message|
        flash[:success] = "Remote Pairing erfolgreich"
      end

      result.on_unsupported do
        flash[:alert] = "Kartenterminal wird nicht unterstützt"
      end
    end

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: [
          turbo_stream.replace(@card_terminal, partial: "card_terminals/show",
                                               locals: { card_terminal: @card_terminal }),
          turbo_stream.update('flash',  partial: "shared/flash_alert")
        ]
      }
    end
  end

  def reboot
    @card_terminal.rmi.reboot do |result|
      result.on_success do |message|
        flash[:success] = "Reboot gestartet"
      end

      result.on_failure do |message|
        flash[:alert] = "Reboot fehlgeschlagen: " + message
      end

      result.on_unsupported do
        flash[:warning] = "Reboot des Kartenterminals wird nicht unterstützt"
      end
    end

    respond_with(@card_terminal, action: :show)
  end

  def fetch_proxy
    ti_client = @card_terminal&.connector&.ti_client
    if ti_client.present?
      rtic = RISE::TIClient::CardTerminals.new(ti_client: ti_client)
      rtic.get_proxies do |result|
        result.on_success do |message, value|
          proxies = value['proxies'] || []
          proxies.each do |proxy|
            if proxy['cardTerminalIp'] == @card_terminal.ip.to_s ||
               proxy['name'] == @card_terminal.name
               Rails.logger.debug("DEBUG:: fetch_proxy: #{proxy} matches #{@card_terminal}")
              ktp = KTProxies::Crupdator.new(ti_client: ti_client, proxy_hash: proxy)
              if ktp.save
                flash[:success] = "KT-Proxy zugeordnet"
              else
                flash[:alert] = "KT-Proxy konnte nicht angelegt/aktualisiert werden!"
              end
              break
            else
              next
            end
          end
        end
        result.on_failure do |message|
          flash[:alert] = message
        end
      end
    else
      flash[:warning] = "Kein TIClient zugewiesen, kein Abgleich möglich!"
    end
    respond_with(@card_terminal)
  end


  def test_context_form
    @context = @card_terminal.connector&.contexts&.first&.dup || Context.new
    respond_with(@card_terminal)
  end

  def test_context
    if @card_terminal.connector.present?
      context = Context.new(test_context_params)
      ri = Cocard::GetCardTerminals.new(connector: @card_terminal.connector,
                                              context: context,
                                              mandant_wide: false)
      result = ri.call
      if result.success?
        if result.card_terminals.select{|ct| ct.ct_id == @card_terminal.ct_id}.any?
          flash.now[:success] = "Kontext-Test erfolgreich: " + context.to_s
        else
          flash.now[:warning] = "Kontext-Test nur teilweise erfolgreich: Kontext gültig, aber Kartenterminal nicht dem Arbeitplatz zugewiesen"
        end
      else
        flash.now[:alert] = "Kontext-Test fehlgeschlagen! " + result.error_messages.join("; ")
      end
    else
      flash.now[:alert] = "Kein Konnektor zugewiesen, kein Kontext-Test möglich"
    end
    respond_with(@connector) do |format|
      format.turbo_stream
    end
  end

  def new_arp
  end

  def arp_check
    arp = params[:arp_list]
    entries = arp.strip.split(/\n/)
    entries.map{|x| x.split(/\s+/)}.each do |ip,mac|
      next if mac.downcase !~ /[0-9a-f]{2}:/
      ct = CardTerminal.where(mac: mac).first
      if ct.present? and ct.ip.to_s == ip.to_s
        unless params[:only_differences]
          msg = "Kartenterminal #{ct.mac} gefunden, IP #{ip} ok"
          poster(:success, ip, mac, ct, msg) 
        end
      elsif ct.present?
        msg = "Kartenterminal #{ct.mac} gefunden, aber mit abweichender IP #{ip} (Cocard: #{ct.ip})"
        poster(:warning, ip, mac, ct, msg)
      elsif CardTerminal.where(ip: ip).any?
        msg = "Kartenterminal #{mac} per MAC nicht gefunden, aber IP #{ip} existiert in Cocard"
        poster(:warning, ip, mac, ct, msg)
      else
        msg = "Kartenterminal nicht gefunden, weder per MAC #{mac} noch per IP #{ip}"
        poster(:danger, ip, mac, ct, msg)
      end
    end;nil
    render :new_arp
  end

  # DELETE /card_terminals/1
  def destroy
    unless @card_terminal.soft_delete
      flash[:alert] = @card_terminal.errors.full_messages.join("; ")
    end
    respond_with(@card_terminal, location: polymorphic_path([@locatable, :card_terminals]))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_terminal
      @card_terminal = CardTerminal.with_deleted.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def card_terminal_params
      params.require(:card_terminal)
            .permit(:tag_list_input,
                    current_ability
                    .permitted_attributes(:update, (@card_terminal||CardTerminal.new)))
            .reject {|k,v| k == 'mac' && v.blank? }

    end

    def idle_message_params
      params.require(:card_terminal).permit(:idle_message)
    end

    def search_params
      searchparms = params.permit(*submit_parms, CardTerminal.attribute_names,
                                  :acknowledged, :with_smcb, :failed, :deleted,
                                  :limit).to_h
      searchparms.reject do |k, v|
        v.blank? || submit_parms.include?(k) || non_search_params.include?(k)
      end
    end

    def submit_parms
      [ "utf8", "authenticity_token", "commit", "format", "view" ]
    end

    def non_search_params
      [ ]

app/views/card_terminals/_cards.html.erb
<div class="table-responsive">
<%= content_tag :table, id: "card_terminal_cards_table",
      class: "table table-sm" do %>
  <thead>
    <tr>
      <th class="text-center"><%= t('attributes.condition') %></th>
      <th><%= t('attributes.name') %></th>
      <th><%= t('attributes.card_type') %></th>
      <th><%= t('attributes.iccsn') %></th>
      <th class="text-center"><%= t('attributes.slotid') %></th>
      <th><%= t('attributes.insert_time') %></th>
      <th><%= t('attributes.expiration_date') %></th>
      <th><%= t('attributes.operational_state') %></th>
    </tr>
  </thead>
  <tbody>
    <% cards.each do |card| %>
      <%= content_tag(:tr, id: dom_id(card)) do %>
        <td class="text-center">
          <%= render ConditionIconComponent.new(item: card, small: true) %>
          <span style="visibility:hidden;"><% card.condition %></span>
        </td>
        <td><%= card.name %></td>
        <td><%= card.card_type %></td>
        <td><%= link_to card.iccsn, card_path(card), class: 'primary-link' %></td>
        <td class="text-center"><%= card.slotid %></td>
        <td><%= card.insert_time %></td>
        <td><%= render ExpirationDateComponent.new(item: card) %></td>
        <td><%= card.operational_state %></td>
      <% end %>
    <% end %>
  </tbody>
<% end %>
</div>

app/views/card_terminals/_idle_message.html.erb
<% if card_terminal.supports_rmi? %>
  <% if card_terminal.tcp_port_open?(card_terminal.rmi_port) %>
    <td id="<%= "idle_message_" + dom_id(card_terminal) %>" data-turbo-prefetch="false" >
      <span class="pe-4"><%= card_terminal.idle_message %></span>
      <% if can? :manage, card_terminal %>
        <%= link_to(edit_idle_message_card_terminal_path(card_terminal),
                    title: t('cocard.edit'),
                    class: "btn btn-sm btn-warning",
                    data: { "turbo-frame": 'modal' }) do %>
            <i class="fa-solid fa-pencil"></i>
        <% end %>
        <%= button_to(fetch_idle_message_card_terminal_path(card_terminal),
                      method: :post,
                      title: t('cocard.reload'),
                      class: "btn btn-sm btn-warning",
                      data: { "turbo-frame": false }) do %>
            <i class="fa-solid fa-rotate-right"></i>
        <% end %>
      <% end %>
    </td>
  <% else %>
    <td id="<%= "idle_message_" + dom_id(card_terminal) %>" data-turbo-prefetch="false" >
      <span class="pe-4"><%= card_terminal.idle_message %></span>
    </td>
  <% end %>
<% else %>
  <td><em><%= t('cocard.card_terminal_rmi_not_supported') %></em></td>
<% end %>

app/views/card_terminals/_index.html.erb
<%= render 'shared/turbo-cache-control' %>

<h1><%= t('controller.card_terminals') %></h1>

<div data-controller="datatables">
  <%= content_tag :table, role: :datatable,
        id: "card_terminals_table",
        class: "table table-bordered table-responsive",
        data: {
          'datatables-target': 'datatable',
          order: [[0, 'asc']].to_json
        } do %>
    <thead>
      <tr>
            <th class="text-center"><%= t('attributes.condition') %></th>
            <th class="notvisible"><%= t('attributes.condition_message') %></th>
            <th><%= t('attributes.displayname') %></th>
            <th><%= t('attributes.ct_id') %></th>
            <th><%= t('attributes.connector') %></th>
            <th class="notvisible"><%= t('attributes.name') %></th>
            <th><%= t('attributes.mac') %></th>
            <th><%= t('attributes.ip') %></th>
            <th><%= t('attributes.connected') %></th>
            <th><%= t('attributes.location') %></th>
            <th><%= t('attributes.room') %></th>
            <th><%= t('attributes.plugged_in') %></th>
            <th><%= t('attributes.contact') %></th>
            <th class="notvisible"><%= t('attributes.idle_message') %></th>
            <th class="notvisible"><%= t('attributes.delivery_date') %></th>
            <th class="notvisible"><%= t('attributes.supplier') %></th>
            <th class="notvisible"><%= t('attributes.serial') %></th>
            <th class="notvisible"><%= t('attributes.id_product') %></th>
            <th><%= t('attributes.firmware_version') %></th>
            <th class="notvisible"><%= t('attributes.description') %></th>
            <th class="notvisible"><%= t('attributes.pin_mode') %></th>
            <th class="notvisible">SMC-KT <%= t('attributes.iccsn') %></th>
            <th class="notvisible">SMC-KT <%= t('attributes.expiration_date') %></th>
            <th><%= t('attributes.last_check') %></th>
            <th><%= t('attributes.last_ok') %></th>
            <th class="nosort"><%= t('cocard.action') %></th>
      </tr>
    </thead>
    <tfoot class="search">
      <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th class="nosearch"></th>
      </tr>
    </tfoot>
    <tbody>
      <% @card_terminals.each do |card_terminal| %>
        <%= content_tag(:tr, id: dom_id(card_terminal), class: dom_class(card_terminal)) do %>
          <td class="text-center">
            <%= render ConditionIconComponent.new(item: card_terminal, small: true, as_text: true) %>
            <span style="visibility:hidden;"><%= card_terminal.condition %></span>
          </td>
          <td><%= card_terminal.condition_message %></td>
          <td><%= link_to card_terminal.displayname, card_terminal_path(card_terminal),
                          class: 'primary-link'  %></td>
          <td><%= link_to card_terminal.ct_id, card_terminal_path(card_terminal),
                          class: 'primary-link'  %></td>
          <td><%= link_to(card_terminal.connector&.name,
                          connector_path(card_terminal.connector),
                          class: 'primary-link'
                         ) if card_terminal.connector %></td>
          <td><%= card_terminal.name %></td>
          <td><%= card_terminal.mac %></td>
          <td><%= card_terminal.ip %></td>
          <td><%= card_terminal.connected %></td>
          <td><%= card_terminal.location %></td>
          <td><%= card_terminal.room %></td>
          <td><%= card_terminal.plugged_in %></td>
          <td><%= card_terminal.contact %></td>
          <td><%= card_terminal.idle_message %></td>
          <td><%= card_terminal.delivery_date %></td>
          <td><%= card_terminal.supplier %></td>
          <td><%= card_terminal.serial %></td>
          <td><%= card_terminal.id_product %></td>
          <td><%= card_terminal.firmware_version %></td>
          <td><%= card_terminal.description %></td>
          <td><%= t(card_terminal.pin_mode, scope: 'pin_modes') %></td>
          <td><%= card_terminal.smckt&.iccsn %></td>
          <td><%= render ExpirationDateComponent.new(item: card_terminal.smckt) %></td>
          <td><%= render IsCurrentComponent.new(item: card_terminal, attr: :last_check) %></td>
          <td><%= render IsCurrentComponent.new(item: card_terminal, attr: :last_ok) %></td>
          <td class="text-nowrap">
            <%= show_link card_terminal %>
            <%= edit_link card_terminal %>
            <%= delete_link card_terminal %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  <% end %>
</div>

<br />

<%= back_link %>

app/views/card_terminals/index.html.erb
<%= render 'shared/turbo-cache-control' %>

<h1><%= t('controller.card_terminals') %></h1>
<p><%= @locatable %></p>

<div id="card_terminals">
  <div data-controller="datatables"
       data-datatables-url-value="<%= card_terminals_path((@filter|| {}).merge(format: :json))%>">
    <%= content_tag :table, role: :datatable,
          id: "card_terminals_table",
          class: "table table-bordered table-responsive",
          data: {
            order: [[0, 'asc']].to_json
          } do %>
      <thead>
        <tr>
              <th class="text-center"><%= t('attributes.condition') %></th>
              <th class="notvisible"><%= t('attributes.condition_message') %></th>
              <th><%= t('attributes.displayname') %></th>
              <th><%= t('attributes.ct_id') %></th>
              <th><%= t('attributes.connector') %></th>
              <th class="notvisible"><%= t('attributes.name') %></th>
              <th><%= t('attributes.mac') %></th>
              <th><%= t('attributes.ip') %></th>
              <th><%= t('attributes.connected') %></th>
              <th><%= t('attributes.location') %></th>
              <th class="nosort"><%= t('controller.tags') %></th>
              <th><%= t('attributes.room') %></th>
              <th><%= t('attributes.plugged_in') %></th>
              <th><%= t('attributes.contact') %></th>
              <th class="notvisible"><%= t('attributes.idle_message') %></th>
              <th class="notvisible"><%= t('attributes.delivery_date') %></th>
              <th class="notvisible"><%= t('attributes.supplier') %></th>
              <th class="notvisible"><%= t('attributes.serial') %></th>
              <th class="notvisible"><%= t('attributes.id_product') %></th>
              <th><%= t('attributes.firmware_version') %></th>
              <th class="nosort notvisible"><%= t('attributes.description') %></th>
              <th class="notvisible"><%= t('attributes.pin_mode') %></th>
              <th class="nosort notvisible">SMC-KT <%= t('attributes.iccsn') %></th>
              <th class="nosort notvisible">SMC-KT <%= t('attributes.expiration_date') %></th>
              <th><%= t('attributes.last_check') %></th>
              <th><%= t('attributes.last_ok') %></th>
              <th class="notvisible"><%= t('attributes.uptime_total') %></th>
              <th class="notvisible"><%= t('attributes.uptime_reboot') %></th>
              <th class="notvisible"><%= t('attributes.slot1_plug_cycles') %></th>
              <th class="notvisible"><%= t('attributes.slot2_plug_cycles') %></th>
              <th class="notvisible"><%= t('attributes.slot3_plug_cycles') %></th>
              <th class="notvisible"><%= t('attributes.slot4_plug_cycles') %></th>
              <th class="nosort"><%= t('cocard.action') %></th>
        </tr>
      </thead>
      <tfoot class="search">
        <tr>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th class="nosearch"></th>
              <th class="nosearch"></th>
              <th class="nosearch"></th>
              <th class="nosearch"></th>
              <th class="nosearch"></th>
              <th class="nosearch"></th>
              <th class="nosearch"></th>
        </tr>
      </tfoot>
      <tbody>
      </tbody>
    <% end %>
  </div>
</div>

<br />

<%= back_link %>